"""Add role column to users table

Revision ID: a5943a87dce6
Revises: 
Create Date: 2025-05-07 13:18:55.543653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5943a87dce6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed commands for already existing columns
    # op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False, server_default='default_password'))
    # op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default='user'))
    # op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Workaround for SQLite's lack of ALTER COLUMN support
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(), nullable=True)
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
